version: '2'
services:

  reverseproxy:
    build: ./reverseProxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/letsencrypt:/letsencrypt

  pathfinding:
      build: ./pathFinding
      depends_on:
        - reverseproxy
      environment:
        - HTTP_PREFIX=/pathFinding
      expose:
        - "9000"

  portfolio:
      build: ./portfolio
      depends_on:
        - reverseproxy
      environment:
        - HTTP_PREFIX=/
      expose:
        - "9000"

  teravia:
    build: ./teravia
    depends_on:
      - reverseproxy
    environment:
      - HTTP_PREFIX=/teravia
    expose:
      - "9000"