version: '2'
services:
  malvapi:
    build: ./MALV-API
    ports:
      - "8080:8080"
  pizzaday:
    build: ./PizzaDay
    expose:
      - "9000"
    volumes:
        - /opt/mongodb/PizzaDay/db:/data/db
  reverseproxy:
    build: ./ReverseProxy
    links:
      - pizzaday
    ports:
      - "80:80"
      - "443:443"