version: '2'
services:

  buildmanager:
    build: ./build-manager
    ports:
      - "8090:8090"
    restart: always

  pathfinding:
    build: ./path-finding
    depends_on:
      - reverseproxy
    environment:
      - HTTP_PREFIX=/pathfinding
    expose:
      - "9000"

  portfolio:
    build: ./portfolio
    depends_on:
      - reverseproxy
    environment:
      - HTTP_PREFIX=/
      - NODE_ENV=production
    expose:
      - "9000"

  reverseproxy:
    build: ./reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/letsencrypt:/letsencrypt

  teravia:
    build: ./teravia
    depends_on:
      - reverseproxy
    environment:
      - HTTP_PREFIX=/teravia
    expose:
      - "9000"