version: '2'
services:

  buildmanager:
    build: https://github.com/josselinbuils/build-manager.git
    ports:
      - "8090:8090"
    restart: always
    volumes:
    - ./build-manager/config.json:/build-manager/config.json

  mongodb:
    image: mongo:latest
    volumes:
        - /opt/mongodb/db:/data/db

  portfolio:
    build: https://github.com/josselinbuils/portfolio.git
    depends_on:
      - reverseproxy
    environment:
      - HTTP_PREFIX=/
    expose:
      - "9000"
    volumes:
    - ./portfolio/config.json:/portfolio/server/config.json

  reverseproxy:
    build: ./reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/letsencrypt:/letsencrypt

  teravia:
    build: https://github.com/josselinbuils/teravia.git
    depends_on:
      - reverseproxy
    environment:
      - HTTP_PREFIX=/teravia
    expose:
      - "9000"

  tournoivolley:
    build: ./tournoi-volley
    depends_on:
      - mongodb
      - reverseproxy
    environment:
      - HTTP_PREFIX=/tournoi-volley
    expose:
      - "3000"
    volumes:
        - /opt/mongodb/db:/data/db
