version: '3.7'
services:
  blog:
    build:
      context: https://github.com/josselinbuils/blog.git
      args:
        - HTTP_PREFIX=/blog
    environment:
      - HTTP_PREFIX=/blog
      - NODE_ENV=production
    expose:
      - "3000"

  buildmanager:
    build: https://github.com/josselinbuils/build-manager.git
    expose:
      - "9001"
    ports:
      - "8090:8090"
    restart: always
    volumes:
      - ./build-manager/config.json:/build-manager/config.json

  components:
    build: https://github.com/josselinbuils/components.git
    environment:
      - HTTP_PREFIX=/components
    expose:
      - "9000"

  mongodb:
    image: mongo:4.2
    volumes:
      - /opt/mongodb/db:/data/db

  portfolio:
    build: https://github.com/josselinbuils/portfolio.git
    environment:
      - HTTP_PREFIX=/
      - NODE_ENV=production
    expose:
      - "3000"
    volumes:
      - ./portfolio/assets:/portfolio/public/assets
      - ./portfolio/config.json:/portfolio/config.json
      - ./portfolio/sharedCode.txt:/portfolio/sharedCode.txt

  reverseproxy:
    build: https://github.com/josselinbuils/reverse-proxy.git
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./reverse-proxy/config.json:/reverse-proxy/config.json
      - ./reverse-proxy/greenlock.d:/reverse-proxy/greenlock.d
      - /opt/letsencrypt:/letsencrypt

  teravia:
    build: https://github.com/josselinbuils/teravia.git
    environment:
      - HTTP_PREFIX=/teravia
    expose:
      - "9000"

  tournoivolley:
    build: https://github.com/josselinbuils/tournoi-volley.git
    depends_on:
      - mongodb
      - reverseproxy
    environment:
      - HTTP_PREFIX=/tournoi-volley
    expose:
      - "3000"
    volumes:
      - ./tournoi-volley/config.json:/tournoi-volley/config.json
      - /opt/mongodb/db:/data/db
