version: '2'
services:

  reverseproxy:
    build: ./reverseProxy
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/letsencrypt:/letsencrypt

  teravia:
    build: ./teravia
    depends_on:
      - reverseproxy
    environment:
      - HTTP_PREFIX=/teravia
      - NODE_ENV=production
      - PORT=9000
    expose:
      - "9000"