version: '2'

services:
  malvapi:
    build: ./MALV-API
    ports:
      - "8080:8080"
  pizzaday:
    build: ./PizzaDay
    depends_on:
      - reverseproxy
    expose:
      - "9000"
    volumes:
        - /opt/mongodb/PizzaDay/db:/data/db
  reverseproxy:
    build: ./ReverseProxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/letsencrypt:/letsencrypt