version: '2'
services:

  buildmanager:
    build: ./buildManager
    ports:
      - "8090:8090"

  pathfinding:
    build: ./pathFinding
    depends_on:
      - reverseproxy
    environment:
      - HTTP_PREFIX=/pathFinding
    expose:
      - "9000"

  mongodb:
    build: mongodb
    volumes:
        - /opt/mongodb/pizzaDay/db:/data/db

  pizzaday:
    build: ./pizzaDay
    depends_on:
      - reverseproxy
    environment:
      NODE_ENV: production
    expose:
      - "9000"
    volumes:
        - /opt/mongodb/pizzaDay/db:/data/db

  portfolio:
    build: ./portfolio
    depends_on:
      - reverseproxy
    environment:
      - HTTP_PREFIX=/
    expose:
      - "9000"

  reverseproxy:
    build: ./reverseProxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/letsencrypt:/letsencrypt

  teravia:
    build: ./teravia
    depends_on:
      - reverseproxy
    environment:
      - HTTP_PREFIX=/teravia
    expose:
      - "9000"