version: '2'
services:
  PizzaDay:
    build: ./PizzaDay
    image: PizzaDayImg
    links:
    - MongoDB
    ports:
     - "80:9000"
    volumes:
     - /opt/mongodb/db:/data/db
    depends_on:
     - MongoDB
  MongoDB:
    build: ./MongoDB
    image: MongoDBImg